var myTxt = new Array(

// Тег <a>
"<a href='/'>Giveaway в Инстаграм</a>",
"<a href='/'>Instagram giveaway</a>",
"<a href='/'>Гив в Украина</a>",
"<a href='/'>Гивы в Instagram</a>",
"<a href='/'>Анонсы giveaway</a>",
"<a href='/'>Анонсы гивов</a>",
"<a href='/'>Анонсы гивэвей</a>", 
"<a href='/'>Актуальные Анонсы Giveaway</a>",
"<a href='/'>Анонсы giveaway в Украина</a>",
"<a href='/'>Анонсы гивэвей в Украина</a>",
"<a href='/'>Анонсы гивов и марафонов</a>",
"<a href='/'>Чат с giveaway в Telegram</a>",
"<a href='/'>Организация GIVEAWAY в Instagram</a>",
"<a href='/'>Проведение конкурсов в Instagram</a>",
"<a href='/'>Подборка конкурсов Instagram в Telegram</a>",
"<a href='/'>Раскрутка Инстаграм магазина</a>",
"<a href='/'>Раскрутка Инстаграм Украина</a>",
"<a href='/'>Продвижение Инстаграм в Украина</a>",
"<a href='/'>Раскрутка и продвижение Instagram</a>",
"<a href='/'>Продвижение аккаунта в Instagram</a>", 
"<a href='/'>Менеджер по Giveaway</a>",  
"<a href='/'>Giveaway в Інстаграм</a>",
"<a href='/'>Instagram giveaway</a>",
"<a href='/'>Гів в Україні</a>",
"<a href='/'>Гіви в Instagram</a>",
"<a href='/'>Анонси giveaway</a>",
"<a href='/'>Анонси гівів</a>",
"<a href='/'>Анонси гівевей</a>", 
"<a href='/'>Актуальні Анонси Giveaway</a>",
"<a href='/'>Анонси giveaway в Україні</a>",
"<a href='/'>Анонси гівевів в Україні</a>",
"<a href='/'>Анонси гівівів і марафонів</a>",
"<a href='/'>Чат з giveaway у Telegram</a>",
"<a href='/'>Організація GIVEAWAY в Instagram</a>",
"<a href='/'>Проведення конкурсів в Instagram</a>",
"<a href='/'>Добірка конкурсів Instagram у Telegram</a>",
"<a href='/'>Розкрутка Інстаграм магазину</a>",
"<a href='/'>Розкрутка Інстаграм Україна</a>",
"<a href='/'>Просування Інстаграм в Україні</a>",
"<a href='/'>Розкрутка і просування Instagram</a>",
"<a href='/'>Просування акаунта в Instagram</a>", 
"<a href='/'>Менеджер з Giveaway</a>",  

// Тег <strong>
"<strong>Giveaway в Инстаграм</strong>",
"<strong>Instagram giveaway</strong>",
"<strong>Гив в Украина</strong>",
"<strong>Гивы в Instagram</strong>",
"<strong>Анонсы giveaway</strong>",
"<strong>Анонсы гивов</strong>",
"<strong>Анонсы гивэвей</strong>", 
"<strong>Актуальные Анонсы Giveaway</strong>",
"<strong>Анонсы giveaway в Украина</strong>",
"<strong>Анонсы гивэвей в Украина</strong>",
"<strong>Анонсы гивов и марафонов</strong>",
"<strong>Чат с giveaway в Telegram</strong>",
"<strong>Организация GIVEAWAY в Instagram</strong>",
"<strong>Проведение конкурсов в Instagram</strong>",
"<strong>Подборка конкурсов Instagram в Telegram</strong>",
"<strong>Раскрутка Инстаграм магазина</strong>",
"<strong>Раскрутка Инстаграм Украина</strong>",
"<strong>Продвижение Инстаграм в Украина</strong>",
"<strong>Раскрутка и продвижение Instagram</strong>",
"<strong>Продвижение аккаунта в Instagram</strong>", 
"<strong>Менеджер по Giveaway</strong>",  
"<strong>Giveaway в Інстаграм</strong>",
"<strong>Instagram giveaway</strong>",
"<strong>Гів в Україні</strong>",
"<strong>Гіви в Instagram</strong>",
"<strong>Анонси giveaway</strong>",
"<strong>Анонси гівів</strong>",
"<strong>Анонси гівевей</strong>", 
"<strong>Актуальні Анонси Giveaway</strong>",
"<strong>Анонси giveaway в Україні</strong>",
"<strong>Анонси гівевів в Україні</strong>",
"<strong>Анонси гівівів і марафонів</strong>",
"<strong>Чат з giveaway у Telegram</strong>",
"<strong>Організація GIVEAWAY в Instagram</strong>",
"<strong>Проведення конкурсів в Instagram</strong>",
"<strong>Добірка конкурсів Instagram у Telegram</strong>",
"<strong>Розкрутка Інстаграм магазину</strong>",
"<strong>Розкрутка Інстаграм Україна</strong>",
"<strong>Просування Інстаграм в Україні</strong>",
"<strong>Розкрутка і просування Instagram</strong>",
"<strong>Просування акаунта в Instagram</strong>",
"<strong>Менеджер з Giveaway</strong>", 

// Тег <b>
"<b>Giveaway в Инстаграм</b>",
"<b>Instagram giveaway</b>",
"<b>Гив в Украина</b>",
"<b>Гивы в Instagram</b>",
"<b>Анонсы giveaway</b>",
"<b>Анонсы гивов</b>",
"<b>Анонсы гивэвей</b>", 
"<b>Актуальные Анонсы Giveaway</b>",
"<b>Анонсы giveaway в Украина</b>",
"<b>Анонсы гивэвей в Украина</b>",
"<b>Анонсы гивов и марафонов</b>",
"<b>Чат с giveaway в Telegram</b>",
"<b>Организация GIVEAWAY в Instagram</b>",
"<b>Проведение конкурсов в Instagram</b>",
"<b>Подборка конкурсов Instagram в Telegram</b>",
"<b>Раскрутка Инстаграм магазина</b>",
"<b>Раскрутка Инстаграм Украина</b>",
"<b>Продвижение Инстаграм в Украина</b>",
"<b>Раскрутка и продвижение Instagram</b>",
"<b>Продвижение аккаунта в Instagram</b>", 
"<b>Менеджер по Giveaway</b>",  
"<b>Giveaway в Інстаграм</b>",
"<b>Instagram giveaway</b>",
"<b>Гів в Україні</b>",
"<b>Гіви в Instagram</b>",
"<b>Анонси giveaway</b>",
"<b>Анонси гівів</b>",
"<b>Анонси гівевей</b>", 
"<b>Актуальні Анонси Giveaway</b>",
"<b>Анонси giveaway в Україні</b>",
"<b>Анонси гівевів в Україні</b>",
"<b>Анонси гівівів і марафонів</b>",
"<b>Чат з giveaway у Telegram</b>",
"<b>Організація GIVEAWAY в Instagram</b>",
"<b>Проведення конкурсів в Instagram</b>",
"<b>Добірка конкурсів Instagram у Telegram</b>",
"<b>Розкрутка Інстаграм магазину</b>",
"<b>Розкрутка Інстаграм Україна</b>",
"<b>Просування Інстаграм в Україні</b>",
"<b>Розкрутка і просування Instagram</b>",
"<b>Просування акаунта в Instagram</b>",
"<b>Менеджер з Giveaway</b>", 

// Текст 
"Giveaway в Инстаграм",
"Instagram giveaway",
"Гив в Украина",
"Гивы в Instagram",
"Анонсы giveaway",
"Анонсы гивов",
"Анонсы гивэвей", 
"Актуальные Анонсы Giveaway",
"Анонсы giveaway в Украина",
"Анонсы гивэвей в Украина",
"Анонсы гивов и марафонов",
"Чат с giveaway в Telegram",
"Организация GIVEAWAY в Instagram",
"Проведение конкурсов в Instagram",
"Подборка конкурсов Instagram в Telegram",
"Раскрутка Инстаграм магазина",
"Раскрутка Инстаграм Украина",
"Продвижение Инстаграм в Украина",
"Раскрутка и продвижение Instagram",
"Продвижение аккаунта в Instagram",
"Менеджер по Giveaway",  
"Giveaway в Інстаграм",
"Instagram giveaway",
"Гів в Україні",
"Гіви в Instagram",
"Анонси giveaway",
"Анонси гівів",
"Анонси гівевей", 
"Актуальні Анонси Giveaway",
"Анонси giveaway в Україні",
"Анонси гівевів в Україні",
"Анонси гівівів і марафонів",
"Чат з giveaway у Telegram",
"Організація GIVEAWAY в Instagram",
"Проведення конкурсів в Instagram",
"Добірка конкурсів Instagram у Telegram",
"Розкрутка Інстаграм магазину",
"Розкрутка Інстаграм Україна",
"Просування Інстаграм в Україні",
"Розкрутка і просування Instagram",
"Просування акаунта в Instagram",
"Менеджер з Giveaway" 


);
randnm=Math.round(Math.random()*(myTxt.length-1));
document.getElementById("words").innerHTML = myTxt[randnm];
